# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
    tags:
      - '**'

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2

      # Use cache
      - name: Cache dependencies and build files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # setup JDK
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        # build only, no test
        run: ./gradlew build -x test -x jar

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2

      # Use cache
      - name: Cache dependencies and build files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # setup JDK
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        id: gradle_test
        run: ./gradlew test
        continue-on-error: true

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: test-report-artifact
          path: ./build/test-results/

      - name: Check on failures
        if: steps.gradle_test.outcome != 'success'
        run: exit 1

  assemble:
    name: Assemble
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2

      # Use cache
      - name: Cache dependencies and build files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # setup JDK
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Assemble jar file
        run: ./gradlew jar

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: jar-artifact
          path: ./build/libs/

  publish:
    name: Publish
    needs: assemble
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v2

      - name: Add a directory for artifacts
        run: mkdir -p ~/artifacts

      - name: Download jar file
        uses: actions/download-artifact@v2
        with:
          name: jar-artifact
          path: ~/artifacts

      - name: Display structure of downloaded files
        run: ls -R ~/artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "~/artifacts/*.jar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}